version: "3"
  
services:
  swnconfluence:
    image: atlassian/confluence-server:7.14
    depends_on:
      - swnpostgresql

    ports:
      - 8087:8090
    environment:
      - JVM_MAXIMUM_MEMORY=4096m
      - ATL_JDBC_URL=jdbc:postgresql://swnpostgresql:5432/confdb
      - ATL_JDBC_USER=confdb
      - ATL_JDBC_PASSWORD=confdb
      - ATL_DB_DRIVER=org.postgresql.Driver
      - ATL_DB_TYPE=postgresql
      - ATL_DB_SCHEMA_NAME=publicconf
 
      
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - swnpostgresql

    environment:
      - PGADMIN_DEFAULT_EMAIL=vb@test.de
      - PGADMIN_DEFAULT_PASSWORD=112233
    ports:
      - 8086:80
      
  swnpostgresql:
    image: postgres:9.6
 
    environment:
      - POSTGRES_USER=confdb
      - POSTGRES_PASSWORD=confdb
      - POSTGRES_DB=confdb
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C.UTF-8
      - POSTGRES_COLLATE_TYPE=C.UTF-8
      - LC_COLLATE=C.UTF-8
      - LC_CTYPE=C.UTF-8
      
 

